name: NotEnoughUpdates REPO Workflow

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master, alpha ]
  push:
    branches: [ master, alpha ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: run-checks
      uses: NotEnoughUpdates/NotEnoughUpdates-REPO-Workflow@main
      with: 
        repo-token: ${{secrets.GITHUB_TOKEN}}
